-- CEK PROMOTOR YANG ADA DI DATABASE
SELECT 
    name,
    id,
    email,
    role,
    status,
    store_id
FROM users
WHERE role = 'promotor'
  AND UPPER(name) IN (
    'ADRIANA',
    'AINI RAHMATINI NATALIA MOESTAKIM',
    'ALDIANA WELIA PANIE',
    'ALITA D PAU',
    'AMBU BAIQ JUMENAH',
    'ANAK AGUNG SRI WULANTIWI',
    'ANGELA BOUKA BERI',
    'ANITA ANA AMAH',
    'ARMINDA TEKU MANEK',
    'ASTUTI BELA WAWO',
    'AZ ZAHRA SITI ZAINAB',
    'DINDA CHRISTANTI',
    'EMPI FRANGKI LIEM',
    'ESTER LUDJI',
    'FREDERIKA ALVONSIA LENGO',
    'HERONIMUS NAMU WALI',
    'IDMAL YUSDIRAN YUSUF',
    'IRENE NOVALIA KADJU',
    'KESIA NATALIA I. BENU',
    'LASTRIANA PALUS',
    'MARATHA MARLINDA FANGGIDAE',
    'MARIA MELAN ANANCE BILI',
    'MARNITHA JUWIKE TIMORATI RUNESI',
    'MERDA PUTRI BUNGSU KENAT',
    'MEXY ALEXANDER HETMINA',
    'NABILA RAHMAWATI',
    'NENY MERLIANTI NA'U',
    'NOVLIANA BARBALINA MISA',
    'NUR FATIMAH MOLBANG',
    'PRETI SISILIA SILA',
    'RESTIANY MARIA LUAN KALI',
    'ROS YANE KANA LUDJI',
    'SANTI MARIA LUKMINI NAHAK',
    'SELVINCE BAKO',
    'SULIS NURAINI INSYATUN',
    'WARDIA',
    'YASINTHA MBU',
    'YOMELIANA MARIA MAGNO',
    'YOVANDA KATRINA NAE',
    'YUNITA TAMELAB'
)
ORDER BY name;

-- CEK PROMOTOR YANG MISSING (tidak ada di database)
SELECT DISTINCT 
    unnest(ARRAY['ADRIANA', 'AINI RAHMATINI NATALIA MOESTAKIM', 'ALDIANA WELIA PANIE', 'ALITA D PAU', 'AMBU BAIQ JUMENAH', 'ANAK AGUNG SRI WULANTIWI', 'ANGELA BOUKA BERI', 'ANITA ANA AMAH', 'ARMINDA TEKU MANEK', 'ASTUTI BELA WAWO', 'AZ ZAHRA SITI ZAINAB', 'DINDA CHRISTANTI', 'EMPI FRANGKI LIEM', 'ESTER LUDJI', 'FREDERIKA ALVONSIA LENGO', 'HERONIMUS NAMU WALI', 'IDMAL YUSDIRAN YUSUF', 'IRENE NOVALIA KADJU', 'KESIA NATALIA I. BENU', 'LASTRIANA PALUS', 'MARATHA MARLINDA FANGGIDAE', 'MARIA MELAN ANANCE BILI', 'MARNITHA JUWIKE TIMORATI RUNESI', 'MERDA PUTRI BUNGSU KENAT', 'MEXY ALEXANDER HETMINA', 'NABILA RAHMAWATI', 'NENY MERLIANTI NA'U', 'NOVLIANA BARBALINA MISA', 'NUR FATIMAH MOLBANG', 'PRETI SISILIA SILA', 'RESTIANY MARIA LUAN KALI', 'ROS YANE KANA LUDJI', 'SANTI MARIA LUKMINI NAHAK', 'SELVINCE BAKO', 'SULIS NURAINI INSYATUN', 'WARDIA', 'YASINTHA MBU', 'YOMELIANA MARIA MAGNO', 'YOVANDA KATRINA NAE', 'YUNITA TAMELAB']) AS promotor_name
EXCEPT
SELECT UPPER(name) FROM users WHERE role = 'promotor';
